### ISSUE TITLE
The astcenc sse2 win32 release build decompress image incorrect

### ISSUE THREAD

**Issue by halx99** [ARM-software/astc-encoder#259] opened 2021-06-09 03:46 UTC
## Build env:
- vs2019 16.10
- cmake 3.19.8

## Note
sse2 release build win64 works fine

## Steps to reproduce:
1. clone the last master of astc-encoder
2. Configure: `cmake -B build -A Win32 -DISA_SSE2=ON`
3. Build: `cmake --build build --config Release --target astcenc-sse2`
4. Decompress with release build: `build\Source\Release\astcenc-sse2.exe -dl ASTC_RGB.astc ASTC_RGB-sse2-release.png`
5. Build: `cmake --build build --config Debug --target astcenc-sse2`
6. Decompress with debug build: `build\Source\Debug\astcenc-sse2.exe -dl ASTC_RGB.astc ASTC_RGB-sse2-debug.png`

## showcase
ASTC_RGB-sse2-release:  
![ASTC_RGB-sse2-release](https://user-images.githubusercontent.com/6977319/121289883-480ad680-c918-11eb-989a-878ddf321348.png)  
ASTC_RGB-sse2-debug:  
![ASTC_RGB-sse2-debug](https://user-images.githubusercontent.com/6977319/121289890-4ccf8a80-c918-11eb-97bc-6c7be0b46f6f.png)

The attachment contains the image file 'ASTC_RGB.astc'

[astcenc-sse2-decbug.zip](https://github.com/ARM-software/astc-encoder/files/6620962/astcenc-sse2-decbug.zip)

**Comment by solidpixel** [comment] 2021-06-09 06:16
Thanks for the bug report - will take a look.

**Comment by solidpixel** [comment] 2021-06-09 07:02
Triage status:

* Linux builds don't reproduce - sse2/4.1/avx2 release builds are all OK.

**Comment by solidpixel** [comment] 2021-06-09 08:01
This looks like a Visual Studio compiler bug in the intrinsic handling. 

```
ASTCENC_SIMD_INLINE vint4 unorm16_to_sf16_dbg(vint4 p)
{
	printf("\nVector 1: "); print(p);
	vint4 fp16_one = vint4(0x3C00);
	vint4 fp16_small = lsl<8>(p);

	printf("\nVector 2: "); print(p);
	vmask4 is_one = p == vint4(0xFFFF);
	vmask4 is_small = p < vint4(4);

	printf("\nVector 3: "); print(p);
	vint4 lz = clz(p) - 16;

	printf("\nVector 4: "); print(p);
	vint4 twon = two_to_the_n(lz + 1);
       ....
```

Prints ...

```
Vector 1: v4_i32:
     65519    65519    65519    65535

Vector 2: v4_i32:
     65519    65519    65519    65535

Vector 3: v4_i32:
     65519    65519    65519    65535

Vector 4: v4_i32:
        16       16       16       16
```

The value of `p` is getting corrupted even though nothing is assigned to it.

**Comment by solidpixel** [comment] 2021-06-09 08:30
Workaround committed to `main` in commit 055acba. I'll file a bug report with Microsoft's compiler team to get a proper fix here.

**Comment by halx99** [comment] 2021-06-09 08:32
Excellent, thanks for your repsone and process so match quickly

**Comment by solidpixel** [comment] 2021-06-09 08:35
No problems - thanks for raising the issue.

**Comment by solidpixel** [comment] 2021-06-09 12:07
A follow on patch was needed to fix a typo in the original fix (had `vint` rather than `vint4` which worked for 4-wide SIMD, but broke for AVX2).

**Comment by halx99** [comment] 2021-06-09 12:47
Got it

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by solidpixel** [comment] 2021-06-09 12:53
Microsoft bug report: 

* https://developercommunity.visualstudio.com/t/x86-32-bit-release-builds-corrupting-SSE/1445836

Standalone reproducer for the above:

* https://github.com/ARM-software/astc-encoder/tree/msvc_clz_bug_repro

**Comment by solidpixel** [comment] 2021-06-09 13:03
Footnotes - the original code works with `/Od`, but fails with `/O1` and `/O2`

**Closed** 2021-06-09 15:12 UTC
Labels: bug
