### ISSUE TITLE
Compressor crash: 139 Error

### ISSUE THREAD

**Issue by LuckyStarProg** [ARM-software/astc-encoder#28] opened 2018-08-16 12:22 UTC
While compressing my normal map texture, it always crash with this error, seems that it happens because of Exhaustive compression mode (with other everything is good).
<img width="365" alt="2018-08-16 15 19 11" src="https://user-images.githubusercontent.com/19596973/44208115-25581380-a168-11e8-8239-4062db3a64b1.png">

**Comment by solidpixel** [comment] 2018-08-16 13:35
Can you provide a reproducer from the command line? It's hard to reproduce without knowing exactly what command line arguments you are using.

**Comment by LuckyStarProg** [comment] 2018-08-16 13:43
I ma using this common line: 
astcenc -t /var/folders/mz/my_zrsxd5fngx5xhmn29w47c0000gn/T/java1534426902500.tmp/conv1534426902501.png /var/folders/mz/my_zrsxd5fngx5xhmn29w47c0000gn/T/tex_photo_frame_01_woodOak_smooth_default_N_decompressed.ktx 4x4 -exhaustive -time -showpsnr

Input PNG file
![tex_photo_frame_01_woodoak_smooth_default_n](https://user-images.githubusercontent.com/19596973/44212194-60137900-a173-11e8-9087-3c57d546d59c.png)

**Comment by solidpixel** [comment] 2018-08-16 20:30
I've tried this command line with the latest master build on Windows, and it completes OK for me. I'll try and find someone with a Mac who can build and test the latest version; it's possible that the Mali Texture Compression Tool is shipping with an older binary which is buggy.

**Comment by solidpixel** [comment] 2019-06-25 21:49
Closing - cannot reproduce.

**Closed by solidpixel** 2019-06-25 21:49 UTC
