### ISSUE TITLE
Questions about ASTC compression in two special cases

### ISSUE THREAD

**Issue by Cyrisub** [ARM-software/astc-encoder#430] opened 2023-08-25 12:28 UTC
1. When using ASTC with mask textures, i found that the edges of rgb color were significantly blocky because of the alpha translucency. i tried to use `-a 2` option but astcenc produced identical results. Does `-a` option need to build from source with some defines? And how should i measure the radius properly?
2. When using ASTC with low resolution textures like under 256 pixels width, it seems that even 4x4 block size would be too blocky and blur textures a lot. Does that means i should use other less-lost compression format or just leave them uncompressed?

**Comment by solidpixel** [comment] 2023-08-25 20:11
> When using ASTC with mask textures, i found that the edges of rgb color were significantly blocky because of the alpha translucency.

Can you share an example texture (uncommpressed input so I can try to reproduce here)? 

In general for alpha transparency you want to extrude the edge color value in to the transparent region. Filling transparent areas with e.g. black or white tends to be a bad solution (and fails with post-multiplied blending used in GPUs when filtered, even without compression).

Failing that I would suggest tweaking the channel weighting for mask textures using the `-cw` option to reduce the channel weight assigned to alpha. The compression can struggle with rapid opaque-to-transparent alpha transitions because the alpha diff tends to be large and dwarf the color values. 

> When using ASTC with low resolution textures like under 256 pixels width, it seems that even 4x4 block size would be too blocky and blur textures a lot. 

Why does texture resolution matter? A 4x4 block is a 4x4 block, no matter if the image is 2Kx2K or 16x16. Compress everything.

**Comment by Cyrisub** [comment] 2023-08-28 01:30
I just use the example picture you have used in #208 with latest v4.5.0 build. the original picture i download from github is:
![test](https://github.com/ARM-software/astc-encoder/assets/52318617/2529d425-ba8a-4b21-8b3c-933283dae61c)
and i try `astcenc-avx2.exe -cl .\test.png test0.astc 8x8 -thorough` to compress and `.\astcenc-avx2.exe -dl .\test0.astc test0.png` to decompress (using 8x8 to get the block more noticeable) and it produce:
![test0](https://github.com/ARM-software/astc-encoder/assets/52318617/11328a7d-1d31-4a2a-b633-3dd25aae9b56)
Then i try `astcenc-avx2.exe -cl .\test.png test1.astc 8x8 -thorough -a 2` it produce:
![test1](https://github.com/ARM-software/astc-encoder/assets/52318617/e4020f86-7396-4f2e-a48b-83a8e488a83d)
Although they did have different hash (both astc files and png files) but i can hardly tell the `-a 2` option had any effect in the result.

PS: Also i found the `-cl` and `-cs` option also have no effect and you can see the result is gamma mapped again.

**Comment by Cyrisub** [comment] 2023-08-29 03:38
Seems i misunderstood that `-a` option will add edge color extrusion internally. But i still confused what does `-a` actually affect results to improve quality if the mask texture is preprocessed.

**Comment by Cyrisub** [comment] 2023-08-29 10:44
Very glad to heard that we will have an easier way to prevent edge block artifacts, as changing all mask textures with an ideal extrusion would be a tough work in our pipeline.

Back to my second question, in fact we found many issues about using 8x8 block low-resolution images. They are in fact high level mipmaps, so were generated from a box filter, when we render them in mobile platform, the blocky edge often blend color between different sampling areas (same situation in texture atlas) that's why i'm wonderng whether should apply such compression on those small textures.

**Closed** 2023-08-29 12:12 UTC

**Comment by solidpixel** [comment] 2023-08-29 14:25
Also, remember that if you want to go below 6x6, there are non-square sizes you can try which give smaller reductions e.g. 8x5 or 8x6.

**Comment by Cyrisub** [comment] 2023-08-30 02:51
> Low bitrate encodings are mostly useful for low frequency data sources that lack hard edges, such as light maps
In fact the cases we are facing are more challenge as many textures have composite channel like roughness or AO, so the bitrate often cannot fit a satisfying quality. Also we saw many bleeding color issues in unreal's lightmaps using 6x6 block with mipmap resolution reduction and a shadowmask in alpha, which is also annoying. 

Seems that `-cw` option as you mentioned is also apply in internal compression calculatio. I'm wondering maybe we can have an option to control the code bits (or something equal) of every channel, giving more controls of final results in different use cases.

**Comment by solidpixel** [comment] 2023-08-30 08:23
That's not how the encoding works unfortunately - the bitstream can skip encoding channels completely (for a set of specific channel orderings) but for the channels that are encoded it always uses the same number of bits per channel.

**Comment by solidpixel** [comment] 2023-08-30 08:25
> In fact the cases we are facing are more challenge as many textures have composite channel like roughness or AO, so the bitrate often cannot fit a satisfying quality. 

Storing a non-correlated packed channel nearly always needs a higher bitrate - I wouldn't expect 8x8 to be a good fit for these.
