### ISSUE TITLE
Encoder should support reading from 2D array of pixels.  3D block can be for be a special call.

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#161] opened 2020-10-06 04:26 UTC
ASTC on iOS doesn't even support the 3D block format of ASTC, so all encoding even for 3D images needs to be to the 2D block format.   I'd like to be able to hand my images off to the encoder, but the use of 3D arrays complicates that and is a highly unusual case for encoding.   There are many more 2D and 2D array textures to process than 3D.  Even for 3D, I've already got the slices, and just need the encoder to return the blocks corresponding to that slice.

I'd like to be able to just hand a packed array of rgba8unorm, rgba16f, or rgba32f and then have the encoder read and convert that to rgba32f internally.   I tried allocating a series of row pointers in an array, and then taking the address of that, but the release builds aren't happy about that for some reason.

**Comment by alecazam** [comment] 2020-10-06 04:50
Here's an example of how this routine is much simpler to interface with the 2D world, and it supports FP32, and it uses _Float16 to handle conversions, and I moved some of the redundant tests out of the inner loops.  ASTCEnc is the slowest encoder that I work with, and there are many low-handing optimization by simplifying the inner loops.   Neon is also needed, and more simd use of float4 instead of raw 4 float ops.

```
// fetch an imageblock from the input file.
void fetch_imageblock(
	astcenc_profile decode_mode,
	const astcenc_image& img,
	imageblock* pb,	// picture-block to initialize with image data
	const block_size_descriptor* bsd,
	// position in texture.
	int xpos,
	int ypos,
	int zpos,
	astcenc_swizzle swz
) {
	float *fptr = pb->orig_data;
	int xsize = img.dim_x + 2 * img.dim_pad;
	int ysize = img.dim_y + 2 * img.dim_pad;
	int zsize = (img.dim_z == 1) ? 1 : img.dim_z + 2 * img.dim_pad;

	pb->xpos = xpos;
	pb->ypos = ypos;
	pb->zpos = zpos;

	xpos += img.dim_pad;
	ypos += img.dim_pad;
	if (img.dim_z > 1)
	{
		zpos += img.dim_pad;
	}

	float data[6];
	data[4] = 0;
	data[5] = 1;

	if (img.data_type == ASTCENC_TYPE_U8)
	{
#define USE_2D_ARRAY 1
#if USE_2D_ARRAY
        const uint8_t* data8 = static_cast<const uint8_t*>(img.data);
#else
		const uint8_t*** data8 = static_cast<const uint8_t***>(img.data);
#endif
		for (int z = 0; z < bsd->zdim; z++)
		{
            int zi = zpos + z;
            if (zi < 0)
                zi = 0;
            if (zi >= zsize)
                zi = zsize - 1;
            
			for (int y = 0; y < bsd->ydim; y++)
			{
                int yi = ypos + y;
                if (yi < 0)
                    yi = 0;
                if (yi >= ysize)
                    yi = ysize - 1;
                
				for (int x = 0; x < bsd->xdim; x++)
				{
					int xi = xpos + x;
					if (xi < 0)
						xi = 0;
					if (xi >= xsize)
						xi = xsize - 1;
                
#if USE_2D_ARRAY
                    assert(zi == 1);
                    int px = (yi * bsd->xdim + xi);
					float r = (float)data8[px * 4 + 0];
                    float g = (float)data8[px * 4 + 1];
                    float b = (float)data8[px * 4 + 2];
                    float a = (float)data8[px * 4 + 3];
#else
                    float r = data8[zi][yi][4 * xi];
                    float g = data8[zi][yi][4 * xi + 1];
                    float b = data8[zi][yi][4 * xi + 2];
                    float a = data8[zi][yi][4 * xi + 3];
#endif
					data[0] = r / 255.0f;
					data[1] = g / 255.0f;
					data[2] = b / 255.0f;
					data[3] = a / 255.0f;

					fptr[0] = data[swz.r];
					fptr[1] = data[swz.g];
					fptr[2] = data[swz.b];
					fptr[3] = data[swz.a];

					fptr += 4;
				}
			}
		}
	}
	else if (img.data_type == ASTCENC_TYPE_F16)
	{
#if USE_2D_ARRAY
		const _Float16* data16f = static_cast<const _Float16*>(img.data);
#else
        const _Float16*** data16f = static_cast<const _Float16***>(img.data);
#endif
        
		for (int z = 0; z < bsd->zdim; z++)
		{
            int zi = zpos + z;
            if (zi < 0)
                zi = 0;
            if (zi >= zsize)
                zi = zsize - 1;
            
            for (int y = 0; y < bsd->ydim; y++)
            {
                int yi = ypos + y;
                if (yi < 0)
                    yi = 0;
                if (yi >= ysize)
                    yi = ysize - 1;
                
                for (int x = 0; x < bsd->xdim; x++)
                {
                    int xi = xpos + x;
                    if (xi < 0)
                        xi = 0;
                    if (xi >= xsize)
                        xi = xsize - 1;

#if USE_2D_ARRAY
                    assert(zi == 1);
                    int px = (yi * bsd->xdim + xi);

                    // compiler does _Float16 -> float conversion
                    float rf = (float)data16f[px * 4 + 0];
                    float gf = (float)data16f[px * 4 + 1];
                    float bf = (float)data16f[px * 4 + 2];
                    float af = (float)data16f[px * 4 + 3];
#else
                    // compiler does _Float16 -> float conversion
                    float rf = (float)data16f[zi][yi][4 * xi];
                    float gf = (float)data16f[zi][yi][4 * xi + 1];
                    float bf = (float)data16f[zi][yi][4 * xi + 2];
                    float af = (float)data16f[zi][yi][4 * xi + 3];
#endif
					// equalize the color components somewhat, and get rid of negative values.
					rf = MAX(rf, 1e-8f);
					gf = MAX(gf, 1e-8f);
					bf = MAX(bf, 1e-8f);
					af = MAX(af, 1e-8f);

					data[0] = rf;
					data[1] = gf;
					data[2] = bf;
					data[3] = af;

					fptr[0] = data[swz.r];
					fptr[1] = data[swz.g];
					fptr[2] = data[swz.b];
					fptr[3] = data[swz.a];
					fptr += 4;
				}
			}
		}
	}
    else if (img.data_type == ASTCENC_TYPE_F32)
    {
#if USE_2D_ARRAY
        const float* data32f = static_cast<const float*>(img.data);
#else
        const float*** data32f = static_cast<const float***>(img.data);
#endif
        for (int z = 0; z < bsd->zdim; z++)
        {
            int zi = zpos + z;
            if (zi < 0)
                zi = 0;
            if (zi >= zsize)
                zi = zsize - 1;
            
            for (int y = 0; y < bsd->ydim; y++)
            {
                int yi = ypos + y;
                if (yi < 0)
                    yi = 0;
                if (yi >= ysize)
                    yi = ysize - 1;
                
                for (int x = 0; x < bsd->xdim; x++)
                {
                    int xi = xpos + x;
                    if (xi < 0)
                        xi = 0;
                    if (xi >= xsize)
                        xi = xsize - 1;

#if USE_2D_ARRAY
                    assert(zi == 1);
                    int px = (yi * bsd->xdim + xi);

                    // compiler does _Float16 -> float conversion
                    float rf = (float)data32f[px * 4 + 0];
                    float gf = (float)data32f[px * 4 + 1];
                    float bf = (float)data32f[px * 4 + 2];
                    float af = (float)data32f[px * 4 + 3];
#else
                    float rf = data32f[zi][yi][4 * xi];
                    float gf = data32f[zi][yi][4 * xi + 1];
                    float bf = data32f[zi][yi][4 * xi + 2];
                    float af = data32f[zi][yi][4 * xi + 3];
#endif
                    // equalize the color components somewhat, and get rid of negative values.
                    rf = MAX(rf, 1e-8f);
                    gf = MAX(gf, 1e-8f);
                    bf = MAX(bf, 1e-8f);
                    af = MAX(af, 1e-8f);

                    data[0] = rf;
                    data[1] = gf;
                    data[2] = bf;
                    data[3] = af;

                    fptr[0] = data[swz.r];
                    fptr[1] = data[swz.g];
                    fptr[2] = data[swz.b];
                    fptr[3] = data[swz.a];
                    fptr += 4;
                }
            }
        }
    }

	int rgb_lns = (decode_mode == ASTCENC_PRF_HDR) || (decode_mode == ASTCENC_PRF_HDR_RGB_LDR_A);
	int alpha_lns = decode_mode == ASTCENC_PRF_HDR;

	// impose the choice on every pixel when encoding.
	for (int i = 0; i < bsd->texel_count; i++)
	{
		pb->rgb_lns[i] = rgb_lns;
		pb->alpha_lns[i] = alpha_lns;
		pb->nan_texel[i] = 0;
	}

	imageblock_initialize_work_from_orig(pb,bsd->texel_count);
	update_imageblock_flags(pb, bsd->xdim, bsd->ydim, bsd->zdim);
}

void write_imageblock(
	astcenc_image& img,
	const imageblock* pb,	// picture-block to initialize with image data. We assume that orig_data is valid.
	const block_size_descriptor* bsd,
	// position to write the block to
	int xpos,
	int ypos,
	int zpos,
	astcenc_swizzle swz
) {
	const float *fptr = pb->orig_data;
	const uint8_t *nptr = pb->nan_texel;
	int xsize = img.dim_x;
	int ysize = img.dim_y;
	int zsize = img.dim_z;

	float data[7];
	data[4] = 0.0f;
	data[5] = 1.0f;

	if (img.data_type == ASTCENC_TYPE_U8)
	{
		uint8_t*** data8 = static_cast<uint8_t***>(img.data);
		for (int z = 0; z < bsd->zdim; z++)
		{
			for (int y = 0; y < bsd->ydim; y++)
			{
				for (int x = 0; x < bsd->xdim; x++)
				{
					int xi = xpos + x;
					int yi = ypos + y;
					int zi = zpos + z;

					if (xi >= 0 && yi >= 0 && zi >= 0 && xi < xsize && yi < ysize && zi < zsize)
					{
						if (*nptr)
						{
							// NaN-pixel, but we can't display it. Display purple instead.
							data8[zi][yi][4 * xi] = 0xFF;
							data8[zi][yi][4 * xi + 1] = 0x00;
							data8[zi][yi][4 * xi + 2] = 0xFF;
							data8[zi][yi][4 * xi + 3] = 0xFF;
						}
						else
						{
							data[0] = fptr[0];
							data[1] = fptr[1];
							data[2] = fptr[2];
							data[3] = fptr[3];

							float xcoord = (data[0] * 2.0f) - 1.0f;
							float ycoord = (data[3] * 2.0f) - 1.0f;
							float zcoord = 1.0f - xcoord * xcoord - ycoord * ycoord;
							if (zcoord < 0.0f)
							{
								zcoord = 0.0f;
							}
							data[6] = (astc::sqrt(zcoord) * 0.5f) + 0.5f;

							// clamp to [0,1]
							if (data[0] > 1.0f)
							{
								data[0] = 1.0f;
							}

							if (data[1] > 1.0f)
							{
								data[1] = 1.0f;
							}

							if (data[2] > 1.0f)
							{
								data[2] = 1.0f;
							}

							if (data[3] > 1.0f)
							{
								data[3] = 1.0f;
							}

							// pack the data
							int ri = astc::flt2int_rtn(data[swz.r] * 255.0f);
							int gi = astc::flt2int_rtn(data[swz.g] * 255.0f);
							int bi = astc::flt2int_rtn(data[swz.b] * 255.0f);
							int ai = astc::flt2int_rtn(data[swz.a] * 255.0f);

							data8[zi][yi][4 * xi] = ri;
							data8[zi][yi][4 * xi + 1] = gi;
							data8[zi][yi][4 * xi + 2] = bi;
							data8[zi][yi][4 * xi + 3] = ai;
						}
					}
					fptr += 4;
					nptr++;
				}
			}
		}
	}
	else // if (img.data_type == ASTCENC_TYPE_F16)
	{
		assert(img.data_type == ASTCENC_TYPE_F16);
		uint16_t*** data16 = static_cast<uint16_t***>(img.data);
		for (int z = 0; z < bsd->zdim; z++)
		{
			for (int y = 0; y < bsd->ydim; y++)
			{
				for (int x = 0; x < bsd->xdim; x++)
				{
					int xi = xpos + x;
					int yi = ypos + y;
					int zi = zpos + z;

					if (xi >= 0 && yi >= 0 && zi >= 0 && xi < xsize && yi < ysize && zi < zsize)
					{
						if (*nptr)
						{
							data16[zi][yi][4 * xi] = 0xFFFF;
							data16[zi][yi][4 * xi + 1] = 0xFFFF;
							data16[zi][yi][4 * xi + 2] = 0xFFFF;
							data16[zi][yi][4 * xi + 3] = 0xFFFF;
						}

						else
						{
							data[0] = fptr[0];
							data[1] = fptr[1];
							data[2] = fptr[2];
							data[3] = fptr[3];

							float xN = (data[0] * 2.0f) - 1.0f;
							float yN = (data[3] * 2.0f) - 1.0f;
							float zN = 1.0f - xN * xN - yN * yN;
							if (zN < 0.0f)
							{
								zN = 0.0f;
							}
							data[6] = (astc::sqrt(zN) * 0.5f) + 0.5f;

							int r = float_to_sf16(data[swz.r], SF_NEARESTEVEN);
							int g = float_to_sf16(data[swz.g], SF_NEARESTEVEN);
							int b = float_to_sf16(data[swz.b], SF_NEARESTEVEN);
							int a = float_to_sf16(data[swz.a], SF_NEARESTEVEN);
							data16[zi][yi][4 * xi] = r;
							data16[zi][yi][4 * xi + 1] = g;
							data16[zi][yi][4 * xi + 2] = b;
							data16[zi][yi][4 * xi + 3] = a;
						}
					}
					fptr += 4;
					nptr++;
				}
			}
		}
	}
}
```

**Comment by alecazam** [comment] 2020-10-06 05:14
Above code isn't quite right, but just to convey the idea.  Will repost with working version.

**Comment by solidpixel** [comment] 2020-10-06 07:31
Agreed. This was planned for the new API in 2.0, I just didn't have time to do it. On the plan for 2.1.

**Comment by solidpixel** [comment] 2020-10-06 07:35
Duplicate of #126. Closing.

**Closed by solidpixel** 2020-10-06 07:35 UTC

**Comment by alecazam** [comment] 2020-10-08 17:33
This involves another change, since it looks like one of the variance calcs is going back to data8/data16 values on the source, and doing another conversion to float (and not supporting fp32 input). I'll try to supply that change here when I have a chance.
