### ISSUE TITLE
Windows + Arm64 builds are not invariant with VS2022

### ISSUE THREAD

**Issue by MarkCallow** [ARM-software/astc-encoder#416] opened 2023-06-01 08:58 UTC
I have a situation where our ASTC encoder tests all pass when compiled for and run on Windows with arm64 hardware (ISA_NEON) using VS2022 and MSVC but 13 of them fail when clang-cl  is used instead of MSVC. (All tests pass with both compilers when compiled for and run on x86_64 hardware (ISA_AVX2)).

This got me looking at the FP option settings for invariance. I noticed firstly that no options were being set for ClangCL (see #415) and secondly that "precise" is being used for both invariant and non-invariant cases. Is this correct? 

I fixed the ClangCL option setting issue but even with /fp:precise set, the same set of encoder tests fail. A kind volunteer from Microsoft who is helping us investigate these and similar issues on other platforms has suggested that _strict_ should be used, not _precise_. I tried that but it made no difference.

**Comment by solidpixel** [comment] 2023-06-01 14:39
The settings have been somewhat organically grown, originally to ensure invariance between the various SIMD flavors for x86-64, and later extended to arm64 on macOS. I can entirely believe there are differences based on the compiler build in question. 

> secondly that "precise" is being used for both invariant and non-invariant cases. Is this correct?

"Correct" in as far as it works for the other platforms, including ClangCL for x86-64, based on my testing. I don't have access to arm64 Windows, so that's one I haven't tested.

> that strict should be used

My hope is that precise with contraction disabled is enough to do what we need. Strict is a lot slower (20-25%) so I'm trying to avoid it if possible.

**Comment by solidpixel** [comment] 2023-06-03 08:42
More testing here and it looks like there are issues on x86-64 too.

* VS2019 CL: Fine.
* VS2019 ClangCL: Fails. 
* VS2022 CL precise: Fine.
* VS2022 ClangCL precise: Fails.

**Comment by solidpixel** [comment] 2023-06-04 14:29
Sounds like I guessed correctly. Using the undocumented "-Xclang" option to allow it to also accept GNU-style arguments, setting "-ffp-contract=off" seems to solve the problem.

**Comment by solidpixel** [comment] 2023-06-04 15:26
Workaround to force the contraction mode has been folded into PR #417.

**Comment by solidpixel** [comment] 2023-06-05 09:41
Yeah, loop me in - happy to help if I can. Will talk to our IT and see if I can get hold of a Windows+Arm laptop to test on.

**Comment by solidpixel** [comment] 2023-06-05 09:58
In terms of the fixes for this, I'll merge the current PR without waiting for any Windows+Arm fixes because it definitely does solve issues on x86-64 for me, so is at least forward progress.

**Comment by solidpixel** [comment] 2023-06-09 15:59
Now have a Windows + arm64 laptop I can test on. 

* WSL  g++ 11.3 - all our tests pass.
* WSL clang++ 14.0.0 - all our tests pass
* VS2022 cl.exe - all our tests pass
* VS2022 clangcl.exe - TODO

**Comment by solidpixel** [comment] 2023-06-09 16:08
@MarkCallow Our tests have historically been pretty good at finding invariance issues here, so I suspect the image differences are creeping in prior to compression (e.g. mipgen, etc). Propose closing this one, unless you have an image that reproduces this.

**Comment by MarkCallow** [comment] 2023-06-10 01:40
Let's wait until you've tried clangcl and until I get the next report from Eoin, likely on Monday. Then we can consider closing this.

**Comment by solidpixel** [comment] 2023-06-10 09:50
Our test suite passed on ClangCL too (VS2022 - 15.0.1)

**Comment by solidpixel** [comment] 2023-07-24 22:02
@MarkCallow  Any update on this one? Happy to close?

**Comment by MarkCallow** [comment] 2023-07-27 11:21
Yes you can close this. We are indeed finding issues pre-encoding. These are happening even with the same `INVARIANCE` FP options that you use in your encoder.

**Closed as completed** 2023-07-27 14:09 UTC
Labels: triage
