### ISSUE TITLE
KTX support added is great, but no mipmap support?

### ISSUE THREAD

**Issue by alecazam** [ARM-software/astc-encoder#145] opened 2020-08-14 21:03 UTC
I hoped to call astcenc directly with the new KTX support, but then realized that there's no mip support.  Wasn't the whole point of KTX support over .astc to support mipmaps?   Will switch back to PVRTexTool and cuttlefish instead for now.  PVRTexToolCLI can't call through to the new astcenc as detailed in another issue.

**Comment by solidpixel** [comment] 2020-08-14 21:07
> Wasn't the whole point of KTX support over .astc to support mipmaps?

The whole point of adding KTX support is to support a more standard format, so users can pick up off-the-shelf loaders.

Adding mip support is still in the backlog - just not had time to do it yet.

Closing as duplicate of #74

**Closed by solidpixel** 2020-08-14 21:07 UTC

**Comment by alecazam** [comment] 2020-08-14 23:07
Also note that the problem with this is that PVRTexToolCLI doesn't handle srgb properly, so you end up with totally distorted color values.  I've reported that on the PVR forums for a few years now, but they never seem to validate their output.
