### ISSUE TITLE
Segmentation fault in parse_png_file()

### ISSUE THREAD

**Issue by EnchantedJohn** [ARM-software/astc-encoder#31] opened 2018-08-24 03:25 UTC
Hello,everyone! I use my company tools to fuzz astc.I found a crash in astc on Linux64. I think it is due to parse_png_file().So I will show you some detail information to help you find the leak.

**Comment by EnchantedJohn** [comment] 2018-08-24 03:26
so I use the command is
/home/lx/coverage/testapp/astc/HFL/astcenc -c xxx.png test.astc 6x6 -medium

then there is gdb information:

```
Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:116
116	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:116
#1  0x000000000045e127 in parse_png_file(png*, int, int) ()
#2  0x000000000045fbea in stbi_load_main(stbi*, int*, int*, int*, int) ()
#3  0x0000000000463008 in stbi_load ()
#4  0x000000000044228d in load_image_with_stb(char const*, int, int*) ()
#5  0x00000000004314fd in astc_codec_load_image(char const*, int, int*) ()
#6  0x00000000004022e4 in main ()
(gdb) i r
rax            0xffffffffffff0260	-64928
rbx            0x7fffffffd488	140737488344200
rcx            0x1b10	6928
rdx            0xffffffffffff0267	-64921
rsi            0x7fffffffd4e4	140737488344292
rdi            0x7ffef6fce010	140733042188304
rbp            0xffff0267	0xffff0267
rsp            0x7fffffffbea8	0x7fffffffbea8
r8             0x1b1	433
r9             0xffffffffffff026	1152921504606842918
r10            0x7fffffffbc70	140737488338032
r11            0x7ffff7271a30	140737339922992
r12            0x0	0
r13            0xffffffffffff0267	-64921
r14            0xffff0267	4294902375
r15            0x7fffffffd450	140737488344144
rip            0x7ffff7271ba4	0x7ffff7271ba4 <__memcpy_sse2_unaligned+372>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) x/10i $pc
=> 0x7ffff7271ba4 <__memcpy_sse2_unaligned+372>:	movdqu (%rsi,%rcx,1),%xmm8
   0x7ffff7271baa <__memcpy_sse2_unaligned+378>:	add    $0x1,%r8
   0x7ffff7271bae <__memcpy_sse2_unaligned+382>:	movdqu %xmm8,(%rdi,%rcx,1)
   0x7ffff7271bb4 <__memcpy_sse2_unaligned+388>:	add    $0x10,%rcx
   0x7ffff7271bb8 <__memcpy_sse2_unaligned+392>:	cmp    %r8,%r9
   0x7ffff7271bbb <__memcpy_sse2_unaligned+395>:	ja     0x7ffff7271ba4 <__memcpy_sse2_unaligned+372>
   0x7ffff7271bbd <__memcpy_sse2_unaligned+397>:	cmp    %rax,%rdx
   0x7ffff7271bc0 <__memcpy_sse2_unaligned+400>:	je     0x7ffff7271a6e <__memcpy_sse2_unaligned+62>
   0x7ffff7271bc6 <__memcpy_sse2_unaligned+406>:	movzbl (%rsi,%rax,1),%ecx
   0x7ffff7271bca <__memcpy_sse2_unaligned+410>:	mov    %cl,(%rdi,%rax,1)
```

**Comment by solidpixel** [comment] 2019-07-04 22:13
No means to reproduce this specific issue without the test file to verify that this is fixed, but the upgrade to the new stb_image library in PR #48 solves many cases of corrupt images causing problems.

Closing, as cannot reproduce.

**Closed by solidpixel** 2019-07-04 22:13 UTC
Labels: bug, stbimage
