### ISSUE TITLE
Using -pp-premultiply with sRGB compression gives a brigher than expected output

### ISSUE THREAD

**Issue by ydcoming** [ARM-software/astc-encoder#477] opened 2024-06-21 08:12 UTC
When I convert an image using the command-line tool astcenc with the command astcenc -cs k.png k@1.ktx 6x6 -medium -pp-premultiply, the resulting image appears overly bright when displayed in WebGL.。

However, when I manually handle the pre-multiplication of the Alpha channel using the sharp library in Node.js and then use the command-line tool astcenc with the command astcenc -cs k.png k@1.ktx 6x6 -medium, the image displays correctly in WebGL.

 codes are like this；

``` 
const sharp = require('sharp');
const fs = require('fs').promises;
/// 预乘Alpha操作 png才能使用 所以在使用前先判断通道是否是四个
async function manualPremultiplyAlpha(inputPath, outputPath) {
  try {
    // 读取图像为Raw格式
    const { data, info } = await sharp(inputPath).raw().toBuffer({ resolveWithObject: true });

    // 基于图像的宽度、高度和通道数进行遍历
    const width = info.width;
    const height = info.height;
    const channels = info.channels;
    if (channels !== 4) {
      throw new Error('Input image must have 4 channels (RGBA).');
    }
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        // Calculate the offset of the current pixel in the data array.
        const pixelOffset = (y * width + x) * channels;
        
        // 获取Alpha值并进行归一化（假设8位精度）
        const alpha = data[pixelOffset + 3] / 255;

        // 预乘Alpha操作
        for (let c = 0; c < 3; c++) {
          data[pixelOffset + c] = Math.round(data[pixelOffset + c] * alpha);
        }
      }
    }

   // 使用sharp处理预乘Alpha后的Buffer并输出为PNG
   await sharp(Buffer.from(data), { raw: { width, height, channels } })
   .png()
   .toFile(outputPath);

    console.log('Image processed and saved with manual pre-multiplied alpha.');
  } catch (error) {
    console.error('Error processing image:', error);
  }
}

// 使用函数处理图像
const inputFilePath = 'k.png';
const outputFilePath = 'output.png';
manualPremultiplyAlpha(inputFilePath, outputFilePath);
```

![k](https://github.com/ARM-software/astc-encoder/assets/3353702/736bcc97-682a-48cb-adc8-fad4ebc99136)；

**Comment by ydcoming** [comment] 2024-06-21 08:20
<img width="200" alt="1718957978465" src="https://github.com/ARM-software/astc-encoder/assets/3353702/155860a2-b950-4ee3-9514-7486f6c94f23">

**Comment by solidpixel** [comment] 2024-06-21 13:56
The current code for premul doesn't do anything with color space information, so it's just doing linear-space premul that ignores the sRGB gamma curve. To preserve sRGB data, the correct behavior here in the compressor is going to be a three step preprocess:

* sRGB to linear
* Premul
* Linear to sRGB

**Comment by solidpixel** [comment] 2024-06-21 14:25
Input values into the compressor: 

* Before pre-mul: `1.0000 1.0000 1.0000 0.4941`
* After pre-mul: `0.7315 0.7315 0.7315 0.4941`

This looks correct to me - the 0.7315 in sRGB gamma = 0.4931 in linear gamma.

**Comment by ydcoming** [comment] 2024-06-24 01:37
What are the differences between processing premultiplied alpha using the Sharp library versus Ascent? Although both are supposed to perform premultiplication of the alpha channel, the resulting outputs differ. Furthermore, even though the same API is invoked in both cases, why do different results occur? I am using the LayaAir engine.

**Comment by solidpixel** [comment] 2024-06-24 09:04
No idea - I've never used Sharp or Ascent. However from my point of view, the compressor is currently doing the right thing for sRGB textures, which is applying the pre-multiplication in linear-space. 

If you want the other behavior, which is pre-multiplication in linear-space, use `-cl` not `-cs` when compressing.

**Comment by ydcoming** [comment] 2024-06-24 09:15
My apologies for the confusion in my description. What I meant was, does using the Sharp library for premultiplication, as shown in the code above, result in inconsistencies compared to the algorithm used within the compressor? Does the compressor only support linear premultiplication?

**Comment by solidpixel** [comment] 2024-06-24 09:18
> result in inconsistencies compared to the algorithm used within the compressor

Yes, the code you posted is ignoring color space information, so applying pre-mul in sRGB domain. 

> Does the compressor only support linear premultiplication?

> If you want the other behavior, which is pre-multiplication without sRGB color conversion, use -cl not -cs when compressing.

**Comment by solidpixel** [comment] 2024-06-24 09:20
Also, going back to to an earlier question ... Are you sure these are actually loaded as sRGB ASTC textures in the graphics API? What is the API format being used when you use these at runtime? Compressing with `-cs` only makes sense if you sample from the texture as an sRGB texture.

**Comment by ydcoming** [comment] 2024-06-25 01:52
"Maybe I didn't describe clearly at first. Let me detail my steps now. I conducted a comparison. 
The first group of operations is as follows:
 I used the Sharp library for PremultiplyAlpha, with the code as mentioned earlier. Then I passed the processed image to the compressor with the parameters: 
astcenc -cs output.png k@1.ktx 6x6 -medium. 
The colors appear normal in the LayaAir engine.

The second group of operations is:
 I directly used the compressed PremultiplyAlpha with
 astcenc -cs k.png k@1.ktx 6x6 -medium -pp-premultiply. 
In the LayaAir engine, the brightness is higher. 
What I mean is, there's a difference between how I handled PremultiplyAlpha myself and how the compressor did it."

**Comment by ydcoming** [comment] 2024-06-25 01:59
"I also consulted the official LayaAir engine team. They indeed use the Sharp library first for PremultiplyAlpha and then utilize pvrtextoolcli for texture compression."

**Comment by solidpixel** [comment] 2024-06-25 06:40
Not sure how many ways I can say the same thing.

Stop using astcenc sRGB mode (-cs) in your command line and use linear mode (-cl). Does that work?

**Comment by ydcoming** [comment] 2024-06-25 06:55
yes -cl not work  it didn't work and it turned completely white.

**Comment by solidpixel** [comment] 2024-06-25 06:55
In linear encoding it should look darker - the border goes to 0.4 with premul, instead of 0.7.

**Comment by solidpixel** [comment] 2024-06-25 13:32
Original input image: 
![in](https://github.com/ARM-software/astc-encoder/assets/23016617/33fcc91b-1b4a-4570-93a5-e656bd3e083f)

Output image after compressing with linear-space premultiplication:

`./bin/astcenc-avx2 -tl in.png in-linear-pre.png 6x6 -m
edium -pp-premultiply`

![in-linear-pre](https://github.com/ARM-software/astc-encoder/assets/23016617/ffdb9c49-0b27-4a1f-8986-d5f50a1b70c6)

Output after reading as an sRGB texture and blending: 

![bt-out-l](https://github.com/ARM-software/astc-encoder/assets/23016617/ad8f817c-9a08-47ee-9957-babeeab9ab96)

**Comment by solidpixel** [comment] 2024-06-25 13:34
Your asset pipeline looks to be interpreting the alpha value as being encoded with the sRGB gamma curve, which is unusual. Normally sRGB only applies to the RGB channels (it makes little sense to apply sRGB gamma to non-color data).

**Comment by solidpixel** [comment] 2024-06-25 13:48
This looks like a colorspace issue in your content pipeline and/or application - everything in the compressor seems to working correctly. 

Unless you can point at something specific the compressor is doing wrong, I'm going to close this ticket as the issue is not related to the to compressor behavior.

**Closed as completed** 2024-06-26 09:16 UTC
Labels: triage
