### ISSUE TITLE
issue during the make in MAC os

### ISSUE THREAD

**Issue by vaibhavgupta-bst** [ARM-software/astc-encoder#89] opened 2020-02-20 07:17 UTC
[C++] astc_partition_tables.cpp
astc_percentile_tables.cpp:77:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        61, 84,
        ^~~~~~
        {     }
astc_percentile_tables.cpp:78:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        184, 141,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:79:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        0, 53,
        ^~~~~
        {    }
astc_percentile_tables.cpp:80:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        percentile_arr_4x4_0, percentile_arr_4x4_1
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        {                                         }
astc_percentile_tables.cpp:117:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        91, 104,
        ^~~~~~~
        {      }
astc_percentile_tables.cpp:118:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        322, 464,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:119:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        0, 202,
        ^~~~~~
        {     }
astc_percentile_tables.cpp:120:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        percentile_arr_5x4_0, percentile_arr_5x4_1
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        {                                         }
astc_percentile_tables.cpp:165:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        129, 126,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:166:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        258, 291,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:167:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        0, 116,
        ^~~~~~
        {     }
astc_percentile_tables.cpp:168:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        percentile_arr_5x5_0, percentile_arr_5x5_1
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        {                                         }
astc_percentile_tables.cpp:220:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        165, 145,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:221:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        388, 405,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:222:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        0, 156,
        ^~~~~~
        {     }
astc_percentile_tables.cpp:223:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        percentile_arr_6x5_0, percentile_arr_6x5_1
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        {                                         }
astc_percentile_tables.cpp:282:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        206, 164,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:283:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        769, 644,
        ^~~~~~~~
        {       }
astc_percentile_tables.cpp:284:2: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
        0, 256,
        ^~~~~~
        {     }
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [astc_percentile_tables-avx2.o] Error 1

**Comment by solidpixel** [comment] 2020-02-20 10:42
Thanks for the bug report. Just so we can test the fix, please can you confirm which compiler and version you are using?

**Comment by solidpixel** [comment] 2020-02-20 22:10
Debugging here, and this looks like `clang++`; I can reproduce similar errors with clang 6.0.0. Fixed in commit 8b4142a, and the previous commit also fixes some errors due to float->double type promotion which this version of clang also throws up.

**Closed** 2020-02-20 22:10 UTC
